### 넘파이 가져오기

In [1]:
import numpy as np

### 넘파이 배열 생성하기

In [2]:
x = np.array([1.0,2.0,3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

### 넘파이의 산술 연산

In [3]:
y = np.array([2.0,4.0,6.0])

In [4]:
x+y # 원소별 덧셈(element-wise plus)

array([3., 6., 9.])

In [5]:
x*y # 원소별 곱셈(element-wise product)

array([ 2.,  8., 18.])

In [6]:
x/y

array([0.5, 0.5, 0.5])

In [8]:
x*7 # 브로드 캐스트 연산

array([ 7., 14., 21.])