**어려워 보이지만, 이 문제는 level1이다. 생각보다 쉬울 수가 있다. 어떤 규칙이 분명히 있다고 생각했는데 너무 어렵네**

### 첫번째 접근 방법
 - 서로 다른 세개의 수를 차례대로 A, B, C 라고 하자. ( A < B < C)
 - 그렇다면 B = A + m , C = A + n 이라고 표현 할 수 있고 
 - 세 수의 합을 A+B+C 대신 A + (A+m) + (A+n) 으로 새롭게 표현 할 수 있다. 
 - A + (A+m) + (A+n) = 3A + m + n 이 소수가 되기 위해서는 
 
     (1) m+n이 3을 인수로 갖지 않고, 
     
     (2) A와 (m+n)이 서로소 이면 된다.

In [44]:

def solution(nums): # 숫자들이 들어있는 배열 nums가 매개변수로 주어질 때
    answer_list = [] # 조건을 만족할때 원소를 하나씩 추가할 list 
    
    import numpy as np
    numsA = np.subtract(sorted(nums), min(nums)) # nums를 정렬후, 각 원소들을 nums의 최소값으로 빼준다
    
    for i in range(1,len(numsA)): # 최소를 제외하고 나머지 수들중에서 두개씩을 뽑는다 
        for a in range(i+1,len(numsA)):
            if (numsA[i]+numsA[a])%3!=0: # 그 두의 합을 3으로 나눈 나머지가 0이 아니면 
                if ((numsA[i]+numsA[a])%(np.arange(2,min(nums)+1))).tolist().count(0)==0:
                    # 두수의 합을 '2에서 최소값'에 해당 되는 수들 모두로 나누었을때 0이 되는 값이 없다면 
                    answer_list.append('p') # p를 추가 
    return len(answer_list)
               
            

In [53]:
nums = [1,2,4,8,12]

In [54]:
numsA = np.subtract(sorted(nums), min(nums))
numsA

array([ 0,  1,  3,  7, 11])

In [55]:
solution(nums)

4

In [56]:
np.arange(2,min(nums)+1)

array([], dtype=int64)

In [70]:

def solution(nums): # 숫자들이 들어있는 배열 nums가 매개변수로 주어질 때
    answer_list = [] # 조건을 만족할때 원소를 하나씩 추가할 list 
    
    import numpy as np
    numsA = np.subtract(sorted(nums), min(nums)) # nums를 정렬후, 각 원소들을 nums의 최소값으로 빼준다
    
    for i in range(1,len(numsA)):
        for a in range(i+1,len(numsA)):
            if (numsA[i]+numsA[a])%3!=0 & ((numsA[i]+numsA[a])%(np.arange(1,min(nums)+1))).tolist().count(0)==1:
                answer_list.append('p')
    return len(answer_list)
                        

In [71]:
nums=[1, 2, 4]

In [72]:
solution(nums)

0

In [60]:
numsA = np.subtract(sorted(nums), min(nums))

In [61]:
numsA

array([0, 1, 2, 3])

In [63]:
for i in range(1,len(numsA)):

IndentationError: expected an indented block (2720411562.py, line 1)

In [74]:
(7%np.arange(1,3)).tolist().count(0)

1

In [75]:
np.arange(1,3)

array([1, 2])