크기가 N*N인 행렬 A가 주어진다. 이때, A의 B제곱을 구하는 프로그램을 작성하시오. 수가 매우 커질 수 있으니, A^B의 각 원소를 1,000으로 나눈 나머지를 출력한다.

In [39]:
2 3
1 3 
4 5 
 
    

SyntaxError: invalid syntax (Temp/ipykernel_12412/881604701.py, line 1)

In [62]:
n,m = list(map(int,input().split()))

2 2


**2X2 행렬을 4번 제곱하기**

In [63]:
matrix_n = []

In [64]:
for i in range(n):
    matrix_n.append(list(map(int,input().split())))

1 3
4 5


In [65]:
matrix_n

[[1, 3], [4, 5]]

In [66]:
copy_matrix_n = matrix_n

In [68]:
print(copy_matrix_n)
print(matrix_n)

[[1, 3], [4, 5]]
[[1, 3], [4, 5]]


In [53]:
for i in range(m):
    

In [55]:
matrix_n = np.array(matrix_n)

In [56]:
matrix_n*matrix_n

array([[16,  4],
       [ 9, 16]])

In [59]:
n,m = list(map(int,input().split()))
matrix_n = []
for i in range(n):
    matrix_n.append(list(map(int,input().split())))
import numpy as np
matrix_n = np.array(matrix_n)
(matrix_n*(matrix_n)

2 2
1 3
4 5


array([[ 1,  9],
       [16, 25]])

In [61]:
matrix_n*matrix_n

array([[ 1,  9],
       [16, 25]])